# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Wallace
email: info@willwallace.name
tagline: Graphic design & front-end development
description: > # this means to ignore newlines until "baseurl:"
  Will Wallace is a freelance graphic designer and front-end web developer based in Reading, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willwallace.name" # the base hostname & protocol for your site
twitter_username: wiiiiilllllll
github_username:  wiiiiilllllll

# Build settings
markdown: kramdown
sass:
  style: compressed

# Minibundle plugin
# gems: ['jekyll/minibundle']
# minibundle:
#   minifier_commands:
#     js: /usr/local/lib/node_modules/uglify-js

# Misc
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/